### PR TITLE
Setup Docker and utilize ENV vars for storing the token

### PR DESCRIPTION
**Pull request by sjaks**
This automates deployment 🙂.

#### Usage and testing
Initial setup on a server:
1. Install docker and docker-compose on production server `sudo apt install docker.io docker-compose`
2. Add the server's default user to the docker user group `sudo usermod -aG docker <your_username>`
3. Enable docker service `sudo systemctl enable docker`

Building the docker image and starting the bot:
1. Go to the repo folder
2. Run `docker-compose up` and the image should be built and bot should start

In case there are updates to the bot, you'll need to rebuild the image with `docker-compose up --build`.

If you have questions, please send them to tumppi@tumppi.com.

### CODE REVIEW

**Comment by sjaks** [comment]
This is not an elegant approach. Closing the PR since further changes to the bot will likely introduce wää.

**Comment by sjaks** [comment]
Plz approve this

**Comment by qaamos** [comment]
Naurattaahan se :D

**Comment by sjaks** [comment]
I tested my own code:
```
sami@cloud:~/discordbot (master) $ docker-compose up
Creating network "discordbot_default" with the default driver
Building discord_bot
Step 1/5 : FROM python:3
...
Step 5/5 : CMD [ "python", "./discord_bot.py" ]
...
discord_bot_1  | discord.errors.LoginFailure: Improper token has been passed.
discordbot_discord_bot_1 exited with code 1
```

I think it works, don't trust me tho

**Pull request merged**
